services:
  - type: web
    name: ordem-paranormal-agentes
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
        value: postgresql://postgres:7M1"t0VsSx59@db.yamjiqnfvnlkldbblubu.supabase.co:5432/postgres