services:
  - type: web
    name: ordem-paranormal-agentes
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
        value: postgresql://neondb_owner:npg_X2voHxUK3pzr@ep-nameless-sunset-acvzs9az-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require